version: '3'

volumes:
  p1_mysql:
  p1_static:

services:
  mysql:
    image: mysql:5.7.27
    container_name: p1_mysql
    environment:
      - MYSQL_DATABASE=p1
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - p1_mysql:/var/lib/mysql:rw
    restart: always

  web:
    build:
      context: .
      dockerfile: dockerconfig/dev/web/Dockerfile
    container_name: p1_web
    ports:
      - 9933:9933
    environment:
      - MYSQL_HOST=mysql
    volumes:
      - p1_static:/app/dist
    depends_on:
      - mysql

  nginx:
    build:
      context: .
      dockerfile: dockerconfig/dev/nginx/Dockerfile
    container_name: p1_nginx
    ports:
      - 80:80
    volumes:
      - p1_static:/etc/nginx/post/static
    depends_on:
      - web
    command: nginx -g 'daemon off;'



